"""Remove dropped field from verification_sessions

Revision ID: 004_remove_dropped_field
Revises: 003_add_machine_id_to_transactions
Create Date: 2026-02-23 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '004'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_sessions', 'dropped')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_sessions', sa.Column('dropped', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###