"""Create pickup_inventory table

Revision ID: 007_create_pickup_inventory
Revises: 006_create_pickup_locations
Create Date: 2026-02-25 10:01:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '007'
down_revision = '006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pickup_inventory',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pickup_location_id', sa.Integer(), nullable=False),
        sa.Column('reward_id', sa.Integer(), nullable=False),
        sa.Column('stock', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['pickup_location_id'], ['pickup_locations.id'], ),
        sa.ForeignKeyConstraint(['reward_id'], ['reward_items.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('pickup_location_id', 'reward_id', name='uix_pickup_reward')
    )
    op.create_index(op.f('ix_pickup_inventory_id'), 'pickup_inventory', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pickup_inventory_id'), table_name='pickup_inventory')
    op.drop_table('pickup_inventory')
    # ### end Alembic commands ###